### ISSUE TITLE
issue when trying to manually enter session in the admin interface causes "an error"

### ISSUE THREAD

**Issue by phyushin** [leigh-hackspace/hackspace-management-system-rails#10]
when trying to alter sessions the page just throws pretty useless and non-descript error

**Comment by alexhartley** [comment]
I'm guessing this is on the production machine? We don't want to be showing users anything more than "something went wrong".

In the dev env it will error and show the full stack trace.

**Comment by phyushin** [comment]
yea i know that .. but i was more raising the issue that an error occurred not that it didnt spit out a stack trace xD

**Comment by alexhartley** [comment]
>when trying to alter sessions the page just throws pretty useless and non-descript error

Well, why comment this then? :smile:

**Comment by pacharanero** [comment]
girls... girls... no fighting in the Issues

**Comment by phyushin** [comment]
i was saying it more as a "and that's all the info i have" than a "im not happy about that" statement

**Comment by alexhartley** [comment]
(╯°□°）╯︵ ┻━┻)

**Comment by phyushin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zY3xQYWe&#x2F;2-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> issues</a>
