### ISSUE TITLE
Admin add user page is not looking good. Or even functional.

### ISSUE THREAD

**Issue by alexhartley** [leigh-hackspace/hackspace-management-system-rails#4]
I'm not sure why but it currently looks like this:

![](http://cdn2.dropmark.com/9456/c327a7ed1ab3ec47aa85a3b266d4d5b9a3cd8569/Screenshot%202016-04-24%2017.45.18.png)

**Comment by phyushin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zY3xQYWe&#x2F;2-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> issues</a>
