### ISSUE TITLE
admin page uses incorrect images

### ISSUE THREAD

**Issue by phyushin** [leigh-hackspace/hackspace-management-system-rails#6]
need to change it to use images for the hackspace

**Comment by alexhartley** [comment]
Do you mean the massive Notting hack banner? :smile:

**Comment by phyushin** [comment]
haha  yes

**Comment by phyushin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zY3xQYWe&#x2F;2-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> issues</a>
